import { Montserrat } from "next/font/google";

const montserratFont = Montserrat({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    style: ['normal', 'italic'],
    subsets: ["latin"],
});

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function Cookies(){
    return(
<div className={`Terms px-10 ${montserratFont.className} font-medium flex items-center justify-center flex-col gap-3.5`}>
        <div className="TermsHeadings text-center flax items-center justify-center mt-28">
            <div className="TermsHeading font-bold text-4xl color">Cookies Notice</div>
            <div className="TermsSubHeading font-semibold text-2xl">nicode networks - nicodenetworks.com</div>
        </div>
        <div className="TermsDate">LAST MODIFIED: FEBURARY 11, 2024</div>
        <div className="TermsContent">
            <div>
                <div className="TermsContentHeading font-semibold text-2xl">1. What Are Cookies</div>
                <div className="TermsContentInfo pl-3">As is common practice with almost all professional websites, this site uses cookies,
                <br></br> which are tiny files that are downloaded to your computer, to improve your experience.
                <br></br> This page describes what information they gather,
                 how we use it and why we sometimes need to store these cookies.
                <br></br> We will also share how you can prevent these cookies from being stored 
                <br></br>however, this may downgrade or 'break' certain elements of the sites' functionality.</div>
            </div>
            <div>
                <div className="TermsContentHeading font-semibold text-2xl">2. Use of Cookies</div>
                <div className="TermsContentInfo">Cookies are used on this website to <br></br>
                a. process the user login <br></br>
                b. store information, like customized designs and more
                </div>
            </div>
            <div>
                <div className="TermsContentHeading font-semibold text-2xl">3. User Conduct</div>
                <div className="TermsContentInfo">a. You are responsible for your use of the website and any consequences that may arise from it.
                <br></br>
                b. You agree not to engage in any activity that may interfere with the proper functioning of the website or compromise its security.</div>
            </div>
            <div>
                <div className="TermsContentHeading font-semibold text-2xl">4. Intellectual Property</div>
                <div className="TermsContentInfo">a. All content, including but not limited to text, images, and logos, on nicodenetworks.com is the property of Nicode Networks and is protected by copyright laws.
                <br></br>
                b. The use of the Spotify API and any related trademarks are subject to Spotify's intellectual property rights.</div>
            </div>
            <div>
                <div className="TermsContentHeading"></div>
                <div className="TermsContentInfo"></div>
            </div>
            <div>
                <div className="TermsContentHeading"></div>
                <div className="TermsContentInfo"></div>
            </div>
            <div>
                <div className="TermsContentHeading"></div>
                <div className="TermsContentInfo"></div>
            </div>
        </div>
        <footer className="TermsContentFooter">Copyright © 2024 Nicolas Pfeifer. All rights reserved.</footer>
    </div>
    )
}